version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: techgadget-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: techgadget_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - techgadget_pgdata:/var/lib/postgresql/data

    ports:
      - 5432:5432

volumes:
  techgadget_pgdata: