ALTER TABLE order_items
    DROP CONSTRAINT fk_order_items_on_product;

ALTER TABLE product_reviews
    DROP CONSTRAINT fk_product_reviews_on_order;

CREATE TABLE product_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    original_key  VARCHAR(255)                            NOT NULL,
    thumbnail_key VARCHAR(255),
    is_primary    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

-- product_reviews: add fk order_item_id column & set constraint NOT NULL
ALTER TABLE product_reviews
    ADD order_item_id BIGINT;
ALTER TABLE product_reviews
    ALTER COLUMN order_item_id SET NOT NULL;
ALTER TABLE product_reviews
    ADD CONSTRAINT FK_PRODUCT_REVIEWS_ON_ORDER_ITEM FOREIGN KEY (order_item_id) REFERENCES order_items (id);

-- product_reviews: add multiple unique key on user_id & order_item_id column
ALTER TABLE product_reviews
    ADD CONSTRAINT uc_b78779a8d356760bb3edd3f2e UNIQUE (user_id, order_item_id);

-- product_reviews: drop order_id column
ALTER TABLE product_reviews
    DROP COLUMN order_id;

-- product_reviews: drop NOT NULL constraint on comment column
ALTER TABLE product_reviews
    ALTER COLUMN comment DROP NOT NULL;

-- products: add price column
ALTER TABLE products
    ADD price BIGINT;

-- products : add stock column
ALTER TABLE products
    ADD stock INTEGER;

-- product: update price & stock column
UPDATE products
SET price = price_in_rupiah,
    stock = stock_quantity;

-- products: set price column NOT NULL
ALTER TABLE products
    ALTER COLUMN price SET NOT NULL;

-- products: set stock column NOT NULL
ALTER TABLE products
    ALTER COLUMN stock SET NOT NULL;

-- products: drop columns
ALTER TABLE products
    DROP COLUMN image_url;
ALTER TABLE products
    DROP COLUMN price_in_rupiah;
ALTER TABLE products
    DROP COLUMN stock_quantity;

-- order_items: add
ALTER TABLE order_items
    ADD product_id_snapshot BIGINT;

ALTER TABLE order_items
    ADD product_image_key_snapshot VARCHAR(255);

ALTER TABLE order_items
    ADD product_name_snapshot VARCHAR(255);

ALTER TABLE order_items
    ALTER COLUMN product_id_snapshot SET NOT NULL;

ALTER TABLE order_items
    ALTER COLUMN product_name_snapshot SET NOT NULL;
ALTER TABLE order_items
    DROP COLUMN product_id;

ALTER TABLE product_images
    ADD CONSTRAINT FK_PRODUCT_IMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);