# =========================
# NETWORK
# =========================
bind 0.0.0.0
port 6379

# =========================
# MEMORY MANAGEMENT
# =========================
maxmemory 256mb
maxmemory-policy allkeys-lru

# =========================
# PERSISTENCE
# =========================
appendonly yes
appendfilename "appendonly.aof"

# save snapshot (optional)
save 900 1
save 300 10
save 60 10000

# =========================
# PERFORMANCE
# =========================
tcp-keepalive 60
timeout 0

# =========================
# SECURITY (basic)
# =========================
protected-mode yes

# =========================
# LOGGING
# =========================
loglevel notice